language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab11-frontend
- docker push $DOCKER_USERNAME/se234-lab11-frontend
service: docker
env:
  global:
  - secure: ZQ44kv+9+rFhzsCazJXxlJplL7Ts6Fk1vF+PEnFDtQIAybB+QtJ8NKvl05mfzk91P09aY+D2g0jbcjIlnI0kv5hSpT6c7YmwOFkf5uxFwJpwq/maUsNzAoRPXm3m0FfVeEE3lYWmMqbm87GDvi8psC5UAmPbZ+/5VX9nBA3BDsubS+ilvwn4y/NXSXtM0apc0ObAZCu0NHTplsFsUVv7gJM6p8PxV76U+wcogqfvNiJ1+p3UCkB/1POu1jQDj21mXNB2vqAZG67IZc9FPo67BILxVl4iaNnOtfUf0iKP0yv6Z9ubMMM2d5iraW2rkSELYpZyBtTuwUFbhmBES4MUUHkvExy50WTajHmVdSN4u/+crcQMPM2kmgLabvaJnl4wsClmp3Blg7de1reBRl5VJW5sFoYkAYm83vxtsOScLTHurpScRWnfNzinAfrih5RwCI6Rohio9csG96oXgmwqMTFq5AetgMg6w+WK9NHoz/wptrMOrMf6Yi56VD79HI9EKcVc4DjzL92YH0++mUTrY/ED5KWq+lSX/+Li0SLvM9lWGyu+pS+jzzrdrVhQaSTHyRB5RHiBegw0isJ9khlpN5QK+DKaDmJyuP4R5nnhLIRf7UB6vgRwbqQ7njfz5jXr+mkGcJqrkvPnP+5dYW2KiEZzFGdOq1V5sExv1y7tWo8=
  - secure: n49ZOIXTd8hZJK6XgoTU4zWQ5Ub0OrpYUnK2DpmeG2uGv0IRYrUiHOUYq+5xGfT4ywaTkb5/Ibc6Zdm/PGxQG2qU5l5hZIjuaPdirPtwapyZfXEZ1IpcOXu0IPBkSOu93KorRugwZ3qcJStfnn7llF5DBZNugndMzj8t3AIErBi7sJrJiNuC/UGbSoS+joI5YtXH3OAOh+JS9D0x9QxmAJunyitpIBO2J4RZdJtm6cHM7q/kwvQj75ZSRqXdiXk6KSocGK2U6oyskkSJyUXU3TzU7h9qgxOf+yzI5b3yPvpmaj/oKK0UL65PeImCVrwYvnRAIVrfjuXSJKq3tMzghGohhtOMtDDhMDToO2lllnwiJ7rEUW4t6NbIyPiyoMgjusO0UK3AOpFblnVTe0EyFyt5QphvQfi4TrmOwzLSTTTUpmQhl00KbYhGZSKY6Q2GaswCTGHh5Fpga6hd8y5m7bA1wbwvcj0wbTnsi7kXXZGEndUxQphrfG7sYJwv7niz/kWn4rywxdPm72zvFbAoKeA1LTm4cJedSe2Tx+Kila1LfCEP9V40UqhbGEBkVH+t4OKnHel5lQYghq4zpr7nQGnbaL+VGFddd3it3gc02a7hBn8OqxcFhUFHArYkcu6HCtWUVWxMKvisRFI/mea4dOT02WE/MQsh21ccI1X25GM=
