language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab11-frontend .
- docker push $DOCKER_USERNAME/se234-lab11-frontend
service: docker
env:
  global:
  - secure: CxO+wyRJMH8NVYI5JMCqYd0EQvMdAIiMDBBwat9UOJi7mlsnfi6ZxfoddYW/Il+UqolrCfJmLI783KDT8fFEO13GtFrbIlUZmlBiczNM8KkTe5n3vUMOEVSDC5DwU9dgNErz/mFn+CwV35v5hoCQ67F1wISAztUQ1hwqquHrFHzEU1lloUIIIXTUSKpiB6wh7RKwTSa2vxGlqi63SqyK7xtajfx9znrHdwobER2SWWXZPbIdIbJyJ1K6zku+/Uy5w1ftH13Qkk2Lt2ndar3aCesIXGCFt2NYIM5GbfQe/0OIA/A8qVAeHX8JFnK83rvxjn91V3inispG82m6RHwjWM3wPQhrBIKJZzRB7avpKQCpFRNjK1jV16GOnWZbmwJ1Tvqr268/EEurqc9pe7as55Woq9IO2Kxvy/kWQ5tJ1yMNrWYqLBW6uVQ5IkEL3NAJroek2Dz8NJQ/JxJZIgpCMzXO3NB/pVstkphJeCNctTTYVSbJMVvNK0spNCd/Lp4xNm9leHnYdLVxqwYrlZs3/eaVT6ZLMFIvD59PAH30KBghFeaJbHRuO5wSgUU9BR/3BkDVcrhsyDzSi8pGrdKaNt3DRuZES/seUaxViISMbGPgTZ44jtOn2oKOWO551a+Bbmnk4KYy3puxophvWFcjp+PGFsGfEdvRyU4CU8aSPYA=
  - secure: bf/ZYevDS/ZTHUYwQ50E2XotBKARgnSOmr//Z3ZBqMoA00OTAriKyCvH2JjkUnGESkU0klryP64qlgIh6GM3wKSS3OlEmcK9JT3ySvX037XIbkqFcwcgQa4zv/Zi8x2XcGWH0GOv/+vyHGTcOLP1/8F8ihNhREWybqEyI6hmVo7Nd5xXr2MojaHmiO1JO4tchFORXzHJ5LcIu79ScnBmeGHBXYu2FaWA6C6PThD3aJsqtanV8Lo/GFbeU7+xrKIbVg1f+hnmoAdLr5tHNYPwvvHlZdxeVHgoWE2ebtKIBlzVXwXP9nxmVWIjIr791togGg2ixCguFFTpTkDjT42M5Qfs33NhUwOpsHhkJz1lQBlAcbyyhrYax36pPl/HuMuFs4LV0AKZmenAWfiy0Ekn1Ft7AFQTMt4ZEyIYz8W9h14FUaSMOJA8g5KIjUk/eUli9z5qdxiKPOjboqRI2cvC9kxAcik+WeOwLqdOndmDRaLPIgq/slQcLC+L0hr6r7TTSiy1iVvD3n73AAIEggOKWsexnkjt2iUmcOniELF3GFWKvVLQOiPtPNvR3oMhqYgAAZH6Wa5CSI7wWlBijHJKARWQyI+mCKXh/G0ZWEGPXAbDqNdO2LYuIdLYTRBhbmvhnXDz7+IwrwGQ5VmSLU2fjViSi1uU6q/jHbvgbsC49l0=
