version: '3.3'
services:
  backend:
    image: dto80/234-lab11:latest
    ports:
      - "8087:8080"
    volumes:
      - type: bind
        source: ./xxx
        target: /data
  frontend:
    image: 592115007/se234-lab11-frontend:latest
    ports:
      - "8085:80"
